name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - uses: actions/checkout@v2
    - uses: pnpm/action-setup@v4
      with:
          version: 9
    - name: Install modules
      run: pnpm i
    - name: Run tests
      run: pnpm test
      env:
          POE_ACCESS_KEY: ${{ secrets.POE_ACCESS_KEY }}
